# Generated by Django 3.2.12 on 2022-04-26 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, to='eventlist.User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creator', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('event_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventlist.eventlist')),
            ],
        ),
    ]
