# Generated by Django 3.2.12 on 2022-04-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventlist.user'),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
